name: Feature
description: Top-level platform feature
title: "[Feature] "
labels: ["feature"]
body:
  - type: dropdown
    id: release
    attributes:
      label: Release
      description: Which release bucket does this belong to?
      options:
        - Masters 2026
        - Wallet v1
        - Security Phase 1
        - Platform Hardening
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
    validations:
      required: true

  - type: textarea
    id: outcome
    attributes:
      label: Outcome
      description: What does success look like?
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What is included / excluded?